# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [19]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

s = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A = np.random.randint(0, 100, size=(200, 50))
A

array([[91, 56, 28, ..., 46, 50, 27],
       [20, 90, 71, ..., 99, 29, 16],
       [89, 24, 12, ..., 65, 86,  8],
       ...,
       [39, 35, 53, ..., 72, 82, 82],
       [60, 71, 87, ..., 67, 86, 96],
       [38, 93, 95, ..., 20, 85, 25]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [20]:
B = np.transpose(np.random.permutation(np.transpose(A)))
A

array([[91, 56, 28, ..., 46, 50, 27],
       [20, 90, 71, ..., 99, 29, 16],
       [89, 24, 12, ..., 65, 86,  8],
       ...,
       [39, 35, 53, ..., 72, 82, 82],
       [60, 71, 87, ..., 67, 86, 96],
       [38, 93, 95, ..., 20, 85, 25]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [21]:
C = A[A[:,0:len(A[0]):2].sum(axis=1) > A[:,1:len(A[0]):2].mean()]
C

array([[91, 56, 28, ..., 46, 50, 27],
       [20, 90, 71, ..., 99, 29, 16],
       [89, 24, 12, ..., 65, 86,  8],
       ...,
       [39, 35, 53, ..., 72, 82, 82],
       [60, 71, 87, ..., 67, 86, 96],
       [38, 93, 95, ..., 20, 85, 25]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [22]:
i = np.argmax(A.max(axis=1) - A.min(axis=1))
i

7

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [23]:
D = np.argsort(A.reshape(1, len(A)*len(A[0]))).reshape(len(A),len(A[0])) + 1
D


array([[8461, 3374, 2329, ..., 9022, 5025, 1632],
       [8983, 1773, 5356, ...,   31, 7269, 7042],
       [2842, 2686, 9988, ..., 2866, 2873, 8083],
       ...,
       [7007, 6976, 9180, ..., 7644, 4943, 4414],
       [ 363, 8288, 4728, ..., 1953, 6724, 5823],
       [8646, 6606,  159, ..., 7353, 3928,  505]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [24]:
E = (A - A.min(axis=1)[:, None]) / (A.max(axis=1)[:, None] - A.min(axis=1)[:, None])
E

array([[0.96808511, 0.59574468, 0.29787234, ..., 0.4893617 , 0.53191489,
        0.28723404],
       [0.18556701, 0.90721649, 0.71134021, ..., 1.        , 0.27835052,
        0.1443299 ],
       [0.91752577, 0.24742268, 0.12371134, ..., 0.67010309, 0.88659794,
        0.08247423],
       ...,
       [0.3814433 , 0.34020619, 0.5257732 , ..., 0.72164948, 0.82474227,
        0.82474227],
       [0.60204082, 0.71428571, 0.87755102, ..., 0.67346939, 0.86734694,
        0.96938776],
       [0.3877551 , 0.94897959, 0.96938776, ..., 0.20408163, 0.86734694,
        0.25510204]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [25]:
F = A.reshape(1, len(A), len(A[0]))
np.concatenate((F, 2*F, 3*F, 4*F, 5*F, 6*F, 7*F, 8*F, 9*F, 10*F)).shape

(10, 200, 50)

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [37]:
G = np.concatenate((A[:,0:len(A[0]):2], A[:,1:len(A[0]):2]), axis=1)
G

array([[91, 28, 83, ..., 26, 46, 27],
       [20, 71, 10, ..., 78, 99, 16],
       [89, 12, 93, ..., 54, 65,  8],
       ...,
       [39, 53, 24, ..., 41, 72, 82],
       [60, 87, 76, ..., 15, 67, 96],
       [38, 95, 78, ..., 34, 20, 25]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [67]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 3, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [68]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

1708

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [69]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


KeyboardInterrupt: 

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.